title: "FoggyKitchen Autonomous Database Serverless with Terraform - LESSON 12 - Creating Autonomous DB Serverless with ECPU Compute Model."
description: "In this lesson we delve into the realm of database management, focusing on the creation of Autonomous Database (ADB) Serverless instances using the ECPU (Elastic Compute Processing Unit) Compute Model."
stackDescription: "In this lesson we delve into the realm of database management, focusing on the creation of Autonomous Database (ADB) Serverless instances using the ECPU (Elastic Compute Processing Unit) Compute Model."
schemaVersion: 1.1.0
version: "20201028"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - region

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_ocid
  - adb_password

variables:

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your OCI tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region for your OCI Autonomous Database Serverless"
    type: oci:identity:region:name
    required: true
    visibile: true

  adb_password:
    title: "ADB ADMIN Password"
    description: "Specify the password for OCI Autonomous Database Serverless ADMIN user"
    type: password
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$     
    required: true
    visibile: true

  compartment_ocid:
    title: "Compartment"
    description: "Choose Comparment for OCI Autonomous Database Serverless"
    type: oci:identity:compartment:id
    required: true
    visibile: true 

  